### PR TITLE
Rebuild for Python 3.7, GCC 7, R 3.5.1, openBLAS 0.3.2

### PR DESCRIPTION
**Pull request by xhochy**
Fixes #3

### CODE REVIEW

**Comment by sahmed95** [comment]
Hi, thanks a lot for this. I am going to merge this after testing a fresh install.

**Comment by scopatz** [comment]
Pinging this!

**Comment by mariusvniekerk** [comment]
@conda-forge-admin please rerender

**Comment by xhochy** [comment]
@conda-forge-admin please rerender

**Comment by xhochy** [comment]
@conda-forge-admin please rerender

**Comment by xhochy** [comment]
@conda-forge/pigs This is ready for review/merge.

**Comment by mariusvniekerk** [comment]
@conda-forge-admin please rerender

**Pull request merged**
